# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Forge Properties
minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=1.18.2-40.3.12
forge_version_range=[40,)
loader_version_range=[40,)
mapping_channel=official
mapping_version=1.18.2

# Mod Properties
mod_version=0.0.1+1.18.2
maven_group=net.ramgames
archives_base_name=UseTheTool
mod_id=usethetool
mod_name=UseTheTool
mod_license=MIT
mod_authors=RamGames
mod_description=Forces the player to use the correct tool to mine a block
